language: cpp
compiler:
  - gcc
before_install:
  - cd ..
  - sudo apt-get install libwxgtk2.8-dev
  - git clone git://github.com/golems/${TRAVIS_REPO_SLUG/grip/dart}.git
  - (cd dart; ci/before_install.sh ; cmake .; make && sudo make install)
  - cd grip
before_script: cmake .
script: make
branches:
  only:
    - master
